use Football;
go

BEGIN TRAN
SELECT * FROM TeamOwner;
WAITFOR DELAY '00:00:05';
SELECT * FROM TeamOwner;
COMMIT TRAN

-- DIRTY READ
-- Problem
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
-- Solution
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

-- NON-REPEATABLE READS
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- Solution
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

--- PHANTOM READS
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
--- Solution
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

--- DEADLOCKS
--- Solution
SET DEADLOCK_PRIORITY HIGH;

--- Transaction T2
-- to be executed together with Transaction T1 from task3.sql file
BEGIN TRAN
-- print 'updating Team table...';
UPDATE Team
SET teamName='Univ. Craiova T2', teamLeague='Liga 2'
WHERE id > 0;

WAITFOR DELAY '00:00:05';

-- print 'updating TeamOwner table...';
UPDATE TeamOwner
set fullName='Mitrut Vasile T2', age = 999
WHERE id > 0;
COMMIT TRAN

--- UPDATE CONFLICT
--- Solution

ALTER DATABASE Football SET ALLOW_SNAPSHOT_ISOLATION ON
ALTER DATABASE Football SET READ_COMMITTED_SNAPSHOT ON

ALTER DATABASE Football SET ALLOW_SNAPSHOT_ISOLATION OFF
ALTER DATABASE Football SET READ_COMMITTED_SNAPSHOT OFF

SET TRANSACTION ISOLATION LEVEL SNAPSHOT
-- Transaction T2
BEGIN TRAN
SELECT* FROM TeamOwner;
WAITFOR DELAY '00:00:05';
UPDATE TeamOwner
set fullName='Mitrut Vasile T2', age = 999
WHERE id > 0;
COMMIT TRAN

